# Generated by Django 3.2 on 2023-01-07 10:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('TradeSheet', '0008_auto_20221206_1537'),
    ]

    operations = [
        migrations.AddField(
            model_name='tradesheet',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tradesheet', to=settings.AUTH_USER_MODEL),
        ),
    ]
